// Sanitized projects data generated from files in /projects
// Contains only safe ASCII characters and simple fields so it parses reliably.
window.PROJECTS_DATA = [
  { row: 1, slug: 'bsnl-silver-jubillee-short-1', title: 'BSNL Silver Jubillee Short', url: 'projects/bsnl-silver-jubillee-short-1.html' },
  { row: 2, slug: 'social-alpha-year-end-video-2', title: 'Social Alpha Year End Video', url: 'projects/social-alpha-year-end-video-2.html' },
  { row: 3, slug: 'social-alpha-newsletters-3', title: 'Social Alpha Newsletters', url: 'projects/social-alpha-newsletters-3.html' },
  { row: 4, slug: 'bee-centered-design-4', title: 'Bee Centered Design', url: 'projects/bee-centered-design-4.html' },
  { row: 5, slug: 'imagining-future-interfaces-5', title: 'Imagining Future Interfaces', url: 'projects/imagining-future-interfaces-5.html' },
  { row: 6, slug: 'beautiful-creatures-6', title: 'Beautiful Creatures', url: 'projects/beautiful-creatures-6.html' },
  { row: 7, slug: 'twinkle-twinkle-little-notes-7', title: 'Twinkle Twinkle Little Notes', url: 'projects/twinkle-twinkle-little-notes-7.html' },
  { row: 8, slug: 'shy-guy-8', title: 'Shy Guy', url: 'projects/shy-guy-8.html' },
  { row: 9, slug: 'weather-moodwheel-9', title: 'Weather Moodwheel', url: 'projects/weather-moodwheel-9.html' },
  { row: 10, slug: 'hunar-hive-10', title: 'Hunar Hive', url: 'projects/hunar-hive-10.html' },
  { row: 11, slug: 'fireworks-systems-11', title: 'Fireworks Systems', url: 'projects/fireworks-systems-11.html' },
  { row: 12, slug: 'kalpavriksh-12', title: 'Kalpavriksh', url: 'projects/kalpavriksh-12.html' },
  { row: 13, slug: 'muse-and-melody-13', title: 'Muse and Melody', url: 'projects/muse-and-melody-13.html' },
  { row: 14, slug: 'hasta-mudra-14', title: 'Hasta Mudra', url: 'projects/hasta-mudra-14.html' },
  { row: 15, slug: 'row-beyond-15', title: 'Row Beyond', url: 'projects/row-beyond-15.html' },
  { row: 16, slug: 'smart-shopping-cart-16', title: 'Smart Shopping Cart', url: 'projects/smart-shopping-cart-16.html' },
  { row: 17, slug: 'samsung-agentic-ai-interaction-17', title: 'Samsung Agentic AI Interaction', url: 'projects/samsung-agentic-ai-interaction-17.html' },
  { row: 18, slug: 'lost-in-transit-18', title: 'Lost in Transit', url: 'projects/lost-in-transit-18.html' },
  { row: 19, slug: 'mitid-logo-ar-19', title: 'MITID Logo AR', url: 'projects/mitid-logo-ar-19.html' },
  { row: 20, slug: 'tribal-displacement-20', title: 'Tribal Displacement', url: 'projects/tribal-displacement-20.html' },
  { row: 21, slug: 'nataka-21', title: 'Nataka', url: 'projects/nataka-21.html' },
  { row: 22, slug: 'tailors-and-embroiderers-22', title: 'Tailors and Embroiderers', url: 'projects/tailors-and-embroiderers-22.html' },
  { row: 23, slug: 'classical-sculptures-reimagined-23', title: 'Classical Sculptures Reimagined', url: 'projects/classical-sculptures-reimagined-23.html' },
  { row: 24, slug: 'identity-bloom-24', title: 'Identity Bloom', url: 'projects/identity-bloom-24.html' },
  { row: 25, slug: 'coded-graphic-patterns-25', title: 'Coded Graphic Patterns', url: 'projects/coded-graphic-patterns-25.html' },
  { row: 26, slug: 'paul-janet-clock-26', title: 'Paul Janet Clock', url: 'projects/paul-janet-clock-26.html' },
  { row: 27, slug: 'zathura-poster-27', title: 'Zathura Poster', url: 'projects/zathura-poster-27.html' },
  { row: 28, slug: 'its-trap-28', title: 'Its Trap', url: 'projects/its-trap-28.html' },
  { row: 29, slug: 'wiskas-brand-redesign-29', title: 'Wiskas Brand Redesign', url: 'projects/wiskas-brand-redesign-29.html' },
  { row: 30, slug: 'nuway-messaging-app-design-30', title: 'Nuway Messaging App Design', url: 'projects/nuway-messaging-app-design-30.html' },
  { row: 31, slug: 'fintech-website-design-31', title: 'Fintech Website Design', url: 'projects/fintech-website-design-31.html' },
  { row: 32, slug: 'abhyas-website-design-32', title: 'Abhyas Website Design', url: 'projects/abhyas-website-design-32.html' },
  { row: 33, slug: 'festiveza-app-design-33', title: 'Festiveza App Design', url: 'projects/festiveza-app-design-33.html' }
];
