// Sanitized projects data generated from files in /projects
// Contains only safe ASCII characters and simple fields so it parses reliably.
window.PROJECTS_DATA = [
  { row: 1, slug: 'bsnl-silver-jubillee-short-1', 'Project Name': 'BSNL Silver Jubillee Short', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/bsnl-silver-jubillee-short-1.html' },
  { row: 2, slug: 'social-alpha-year-end-video-2', 'Project Name': 'Social Alpha Year End Video', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/social-alpha-year-end-video-2.html' },
  { row: 3, slug: 'social-alpha-newsletters-3', 'Project Name': 'Social Alpha Newsletters', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/social-alpha-newsletters-3.html' },
  { row: 4, slug: 'bee-centered-design-4', 'Project Name': 'Bee Centered Design', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/bee-centered-design-4.html' },
  { row: 5, slug: 'imagining-future-interfaces-5', 'Project Name': 'Imagining Future Interfaces', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/imagining-future-interfaces-5.html' },
  { row: 6, slug: 'beautiful-creatures-6', 'Project Name': 'Beautiful Creatures', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/beautiful-creatures-6.html' },
  { row: 7, slug: 'twinkle-twinkle-little-notes-7', 'Project Name': 'Twinkle Twinkle Little Notes', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/twinkle-twinkle-little-notes-7.html' },
  { row: 8, slug: 'shy-guy-8', 'Project Name': 'Shy Guy', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/shy-guy-8.html' },
  { row: 9, slug: 'weather-moodwheel-9', 'Project Name': 'Weather Moodwheel', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/weather-moodwheel-9.html' },
  { row: 10, slug: 'hunar-hive-10', 'Project Name': 'Hunar Hive', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/hunar-hive-10.html' },
  { row: 11, slug: 'fireworks-systems-11', 'Project Name': 'Fireworks Systems', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/fireworks-systems-11.html' },
  { row: 12, slug: 'kalpavriksh-12', 'Project Name': 'Kalpavriksh', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/kalpavriksh-12.html' },
  { row: 13, slug: 'muse-and-melody-13', 'Project Name': 'Muse and Melody', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/muse-and-melody-13.html' },
  { row: 14, slug: 'hasta-mudra-14', 'Project Name': 'Hasta Mudra', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/hasta-mudra-14.html' },
  { row: 15, slug: 'row-beyond-15', 'Project Name': 'Row Beyond', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/row-beyond-15.html' },
  { row: 16, slug: 'smart-shopping-cart-16', 'Project Name': 'Smart Shopping Cart', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/smart-shopping-cart-16.html' },
  { row: 17, slug: 'samsung-agentic-ai-interaction-17', 'Project Name': 'Samsung Agentic AI Interaction', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/samsung-agentic-ai-interaction-17.html' },
  { row: 18, slug: 'lost-in-transit-18', 'Project Name': 'Lost in Transit', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/lost-in-transit-18.html' },
  { row: 19, slug: 'mitid-logo-ar-19', 'Project Name': 'MITID Logo AR', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/mitid-logo-ar-19.html' },
  { row: 20, slug: 'tribal-displacement-20', 'Project Name': 'Tribal Displacement', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/tribal-displacement-20.html' },
  { row: 21, slug: 'nataka-21', 'Project Name': 'Nataka', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/nataka-21.html' },
  { row: 22, slug: 'tailors-and-embroiderers-22', 'Project Name': 'Tailors and Embroiderers', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/tailors-and-embroiderers-22.html' },
  { row: 23, slug: 'classical-sculptures-reimagined-23', 'Project Name': 'Classical Sculptures Reimagined', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/classical-sculptures-reimagined-23.html' },
  { row: 24, slug: 'identity-bloom-24', 'Project Name': 'Identity Bloom', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/identity-bloom-24.html' },
  { row: 25, slug: 'coded-graphic-patterns-25', 'Project Name': 'Coded Graphic Patterns', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/coded-graphic-patterns-25.html' },
  { row: 26, slug: 'paul-janet-clock-26', 'Project Name': 'Paul Janet Clock', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/paul-janet-clock-26.html' },
  { row: 27, slug: 'zathura-poster-27', 'Project Name': 'Zathura Poster', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/zathura-poster-27.html' },
  { row: 28, slug: 'its-trap-28', 'Project Name': 'Its Trap', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/its-trap-28.html' },
  { row: 29, slug: 'wiskas-brand-redesign-29', 'Project Name': 'Wiskas Brand Redesign', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/wiskas-brand-redesign-29.html' },
  { row: 30, slug: 'nuway-messaging-app-design-30', 'Project Name': 'Nuway Messaging App Design', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/nuway-messaging-app-design-30.html' },
  { row: 31, slug: 'fintech-website-design-31', 'Project Name': 'Fintech Website Design', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/fintech-website-design-31.html' },
  { row: 32, slug: 'abhyas-website-design-32', 'Project Name': 'Abhyas Website Design', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/abhyas-website-design-32.html' },
  { row: 33, slug: 'festiveza-app-design-33', 'Project Name': 'Festiveza App Design', Category: 'General', Tags: '', Duration: '', Time: '', Featured: 'no', url: 'projects/festiveza-app-design-33.html' }
];
